using System.Net.Http.Headers;using System.Text;using System.Text.Json;using LegalAI.Models;
namespace LegalAI.Services;
public class AiService
{private readonly HttpClient _http;private readonly IConfiguration _cfg;private readonly IWebHostEnvironment _env;public AiService(HttpClient h,IConfiguration c,IWebHostEnvironment e){_http=h;_cfg=c;_env=e;}
 public Task<string> SummarizeAsync(LegalRecord r)=>CallAsync(File.ReadAllText(Path.Combine(_env.ContentRootPath,"prompts/system_prompt.txt")),File.ReadAllText(Path.Combine(_env.ContentRootPath,"prompts/summary_prompt.txt")).Replace("{{legal_document}}",Text(r)),Demo(r));
 public Task<string> ChatAsync(string q,List<LegalRecord> rs){var context=string.Join("\n---\n",rs.Select(Text));return CallAsync(File.ReadAllText(Path.Combine(_env.ContentRootPath,"prompts/system_prompt.txt")),File.ReadAllText(Path.Combine(_env.ContentRootPath,"prompts/chat_prompt.txt")).Replace("{{question}}",q).Replace("{{data}}",context),"AI DEMO: Chưa cấu hình API key. Hệ thống có "+rs.Count+" hồ sơ trong phạm vi quyền của bạn. Câu hỏi: "+q);}
 private async Task<string> CallAsync(string system,string user,string fallback){var key=_cfg["OPENAI_API_KEY"]??Environment.GetEnvironmentVariable("OPENAI_API_KEY");if(string.IsNullOrWhiteSpace(key))return fallback;try{var endpoint=_cfg["OPENAI_ENDPOINT"]??"https://api.openai.com/v1/chat/completions";var model=_cfg["OPENAI_MODEL"]??"gpt-4o-mini";using var req=new HttpRequestMessage(HttpMethod.Post,endpoint);req.Headers.Authorization=new AuthenticationHeaderValue("Bearer",key);req.Content=new StringContent(JsonSerializer.Serialize(new{model,temperature=.2,messages=new[]{new{role="system",content=system},new{role="user",content=user}}}),Encoding.UTF8,"application/json");using var ct=new CancellationTokenSource(TimeSpan.FromSeconds(30));var res=await _http.SendAsync(req,ct.Token);if((int)res.StatusCode==429)return "AI đang bị rate limit. Vui lòng thử lại sau.";if(!res.IsSuccessStatusCode)return $"AI lỗi HTTP {(int)res.StatusCode}.";using var doc=JsonDocument.Parse(await res.Content.ReadAsStringAsync());return doc.RootElement.GetProperty("choices")[0].GetProperty("message").GetProperty("content").GetString()??"AI không trả về nội dung.";}catch(OperationCanceledException){return "AI timeout sau 30 giây.";}catch(JsonException){return "AI trả về dữ liệu sai định dạng.";}catch(Exception e){return "Không thể gọi AI: "+e.Message;}}
 private static string Text(LegalRecord r)=>$"ID:{r.Id}; Tên:{r.Title}; Loại:{r.RecordType}; Phụ trách:{r.ResponsiblePerson}; Phòng:{r.Department}; Hạn:{r.ExpiryDate:yyyy-MM-dd}; Trạng thái:{r.Status}; Nội dung:{r.Content}";
 private static string Demo(LegalRecord r)=>$"AI DEMO\n\n1. Nội dung chính: {r.Content}\n2. Phụ trách: {r.ResponsiblePerson}\n3. Thời hạn: {r.ExpiryDate:dd/MM/yyyy}\n4. Cảnh báo: {(r.ExpiryDate<DateTime.Today.AddDays(30)?"Cần theo dõi sớm.":"Chưa thuộc nhóm 30 ngày")}\n5. Lưu ý: AI chỉ hỗ trợ tra cứu, không thay thế tư vấn pháp lý.";
}
